### ISSUE TITLE
Process continues to live

### ISSUE THREAD

**Issue by Nyarum** [miketheprogrammer/go-thrust#44]
After you close the application - the process remains and begins to take more than 40% CPU.

Webserver and Thrust into a single binary file.

**Comment by miketheprogrammer** [comment]
Yea, i thought we had fixed this, please dont kill the application, only use the SafeExit method, or whatever exit methods have been provided in the thrust file.

Windows it is especially difficult to detect a force quit.

**Comment by miketheprogrammer** [comment]
@Nyarum 
Please see Thrust.Exit() in thrust.go
also please see this for the built in safety that should be firing, note this may not always work in windows.
https://github.com/miketheprogrammer/go-thrust/blob/59ae10c7294fb5ce056b3100311d48c1c9df204b/lib/connection/connection.go#L63

**Comment by Nyarum** [comment]
If use Thrust.Exit() then everything is fine.
Can possibly keep track of the exit window Thrust?

**Comment by miketheprogrammer** [comment]
Thrust should emit an event when a window is closed, but if not, then you can do long polling to check the state of a window.
