### ISSUE TITLE
Any way to remove window frame?

### ISSUE THREAD

**Issue by ktmn** [miketheprogrammer/go-thrust#53]
Basically kiosk, except not full screen.

**Comment by kacpersaw** [comment]
+1

**Comment by miketheprogrammer** [comment]
I do not believe so, I would check the Thrust documentation, im trying to build a team to spend at least some time maintaining thrust.

**Comment by miketheprogrammer** [comment]
I think there is a frameless window. I will have to look into the thrust api

**Comment by miketheprogrammer** [comment]
Haha @ktmn @kacpersaw  I wish you have looked at tutorials. I had a tutorial for frameless windows.
Marking closed.
