### ISSUE TITLE
Error happened when ·go get -v github.com/miketheprogrammer/go-thrust·

### ISSUE THREAD

**Issue by shawnye** [miketheprogrammer/go-thrust#68]
C:\Users\shawn>go get -v github.com/miketheprogrammer/go-thrust
github.com/miketheprogrammer/go-thrust (download)
github.com/miketheprogrammer/go-thrust/lib/common
github.com/miketheprogrammer/go-thrust/lib/commands
github.com/miketheprogrammer/go-thrust/lib/connection
github.com/miketheprogrammer/go-thrust/lib/spawn
·#· github.com/miketheprogrammer/go-thrust/lib/spawn
E:\WORKSPACE\go\libs\src\github.com\miketheprogrammer\go-thrust\lib\spawn\download.go:20: undefined: PathNotExist

**Comment by miketheprogrammer** [comment]
I apologize for the inconvenience guys. I have not had even a moment to
patch it. I will try to patch later from my hotel room if internet is good

**Comment by miketheprogrammer** [comment]
can you try again. Should be fixed. let me know

**Comment by Leprevost** [comment]
hi @miketheprogrammer . I'm still having the same error.

**Comment by tehbilly** [comment]
@Leprevost Try running `go get -u -v github.com/miketheprogrammer/go-thrust/...` to force `go get` to update. Alternatively, delete `${GOPATH}/src/github.com/miketheprogrammer/go-thrust` and try again.

**Comment by Leprevost** [comment]
thanks, that resolved the issue with the installation.

**Comment by tehbilly** [comment]
Cheers! Going to close the issue.

A side note, adding `-u` to `go get` has become second nature to me, because the default of assuming the local version is the version to want leads to issues like this. Give it a try in the future for just about anything you have problems with.
